development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://dashfayserver.herokuapp.com/"
  secret_token: <%= ENV['PRIVATE_PUB'] || "secret_token" %>
  signature_expiration: 3600 # one hour
